version: '3'
vars:
tasks:
  default:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo run
    silent: true
  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo test
    silent: true
  clean:
    cmds:
      - make clean
    silent: true
