version: '3'
vars:
tasks:
  default:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo run -- {{.CLI_ARGS}}
    silent: true
  clippy:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo clippy
    silent: true
  release:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo build --release
    silent: true
  rr:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - $(fd -t x -d 1 . target/release)
    silent: true
  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo test
    silent: true
  clean:
    cmds:
      - scripts/clean.sh
    silent: true
