version: '3'
vars:
tasks:
  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo test
    silent: true
  default:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cargo run
    silent: true
