[package]
name = "scheduler-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
tokio = { version = "1.29.1", features = ["full"] }
